// Code generated by mockery v2.43.2. DO NOT EDIT.

package storagemocks

import (
	mock "github.com/stretchr/testify/mock"
	crossfit "github.com/wodm8/wodm8-core/internal/crossfit"
)

// ExerciseWodRepository is an autogenerated mock type for the ExerciseWodRepository type
type ExerciseWodRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: exerciseWod
func (_m *ExerciseWodRepository) Save(exerciseWod crossfit.ExerciseWod) error {
	ret := _m.Called(exerciseWod)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(crossfit.ExerciseWod) error); ok {
		r0 = rf(exerciseWod)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExerciseWodRepository creates a new instance of ExerciseWodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExerciseWodRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExerciseWodRepository {
	mock := &ExerciseWodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
