name: dev-ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Hello code!!
        run: echo "Hello code!! from ${{ github.repository}} triggered by the ${{github.event_name}} and done by ${{github.actor}}"

      - name: second step!
        env:
          JOB_CONTEXT: ${{toJson(jon)}}
        run: |
          echo "Job context: $JOB_CONTEXT"
          echo "Done!"

        
